One hot encoding
===

One Hot Encoding is normally represented for Numerical or Categorical Data.

This way it makes the data less memory intensive

You can also use other tricks with pandas to optimize this process

### Requirements

In [1]:
import numpy as np

In [26]:
def get_one_hot(input_vector):
    result = []
    for i in input_vector:
        
        # Fill an array with zeros with the size of the biggest values of input_vector + 1 (so that we can count with 0 index) or else if we mark 0 on the array, the 1 will be located
        # In last index. Try it, and practice with it
        newval = np.zeros(max(input_vector) + 1)
        
        # Set the newval in the position of i as 1 value
        newval.itemset(i, 1)
        
        # Append to the result list
        result.append(newval)
    return result

In [27]:
x = [0, 4, 10,3, 4, 4]
get_one_hot(x)

[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])]